project:
  type: website

website:
  title: "Jorge Bris Moreno"
  favicon: images/my_image.jpeg
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: https://github.com/anly501/dsan-5000-project-jbrismor.git
        text: Code 
      - text: Data
        href: index.qmd
      - text: Introduction
        href: Introduction.qmd
      - text: Data Gathering
        href: Data_Gathering.ipynb    
      - text: Data Cleaning
        href: Data_cleaning.ipynb    
      - text: Data Exploration
        href: EDA.ipynb
      - text: Naive Bayes
        href: Naive_Bayes.ipynb     
      - text: Clustering
        href: index.qmd      
      - text: Dimensionality reduction
        href: index.qmd      
      - text: Decision Trees
        menu:
          - text: Classification
            href: index.qmd        
          - text: Regression
            href: index.qmd        
      - text: ARM
        href: index.qmd      
      - text: Conclusions
        href: index.qmd      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
