project:
  type: website

website:
  title: "Jorge Bris Moreno"
  favicon: images/my_image.jpeg
  navbar:
    left:
      - href: index.qmd
        text: About me
      - text: Beyond Moving
        menu:
          - text: Code
            href: https://github.com/anly501/dsan-5000-project-jbrismor/tree/acc8e510980706cfe1e58878f92008ae25e48516/dsan-website/5000-website
          - text: Data
            href: Data.ipynb
          - text: Introduction
            href: Introduction.qmd
          - text: Data Gathering
            href: Data_Gathering.ipynb    
          - text: Data Cleaning
            href: Data_cleaning.ipynb    
          - text: Data Exploration
            href: EDA.ipynb
          - text: Naive Bayes
            href: Naive_Bayes.ipynb     
          - text: Clustering
            href: Clustering.ipynb      
          - text: Dimensionality reduction
            href: Dimension_red.ipynb      
          - text: Decision Trees
            href: trees.ipynb       
          - text: Conclusion
            href: Conclusion.ipynb
  
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
